### ISSUE TITLE
Fizzbuzz level 1 challenge

### ISSUE THREAD

**Issue by chiperific** [WestMichiganRubyTraining/discussion#28]
Alright, I'm looking for a reminder of the lvl 1 challenge opportunity.

Are we completing all steps of the [Fizzbuzz challenge](http://billgathen.com/2013/01/18/7_degrees_of_fizzbuzz.html) or just first five? Through RSpec?

Did you say we have 10 minutes to complete the challenge?

**Comment by ThomasBush** [comment]
@chiperific You have 10 minutes to complete the first 4 steps of the challenge.

**Comment by billgathen** [comment]
Tom is correct. The RSpec step will be part of our new challenge, which you'll train for separately after completing level one.

[HOW TO: Graduate from Fizzbuzz!](https://github.com/WestMichiganRubyTraining/discussion/issues/10) gives full details on the level one challenge.
