### ISSUE TITLE
GR GiveCamp: November 8-10, 2013

### ISSUE THREAD

**Issue by billgathen** [WestMichiganRubyTraining/discussion#33]
All right, I'm in: who's with me?

http://grgivecamp.org

> GiveCamp is a weekend-long event where technology professionals – from designers, developers and database administrators to marketers and web strategists – donate their time to provide solutions for non-profit organizations.

And yes, that's our own @chiperific in their promo video. Yay, Chip!

**Comment by DeLongShot** [comment]
Woohoo!  Great to see Bill.

I will add that this is a great way for people who are new to Ruby to get
some great experience.  I went last year and learned so much just by
working alongside other Ruby devs.

Full transparency, I am on the organizing committee this year, but I would
definitely recommend attending if you are able.

On Tue, Oct 1, 2013 at 2:22 PM, Bill Gathen notifications@github.comwrote:

> All right, I'm in: who's with me?
> 
> http://grgivecamp.org
> 
> GiveCamp is a weekend-long event where technology professionals – from
> designers, developers and database administrators to marketers and web
> strategists – donate their time to provide solutions for non-profit
> organizations.
> 
> And yes, that's our own @chiperific https://github.com/chiperific in
> their promo video. Yay, Chip!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WestMichiganRubyTraining/discussion/issues/33
> .

## 

_Adam DeLong_
Web Developer
Elevator Up
616-915-9286
adam@elevatorup.com

**Comment by atkolkma** [comment]
This is really cool! I hope I can clear some time for this.

Thanks for the heads up, Bill.

-Adam

**Comment by ThomasBush** [comment]
I'm in - just registered. Sounds pretty cool, excited to help however I can!

**Comment by billgathen** [comment]
@ThomasBush Excellent, Tom! Who else is coming?

@DeLongShot Adam, do you have any numbers yet on how many charities, how many techies?

**Comment by coderbydesign** [comment]
I'll be there!

**Comment by DeLongShot** [comment]
@billgathen Non-profits will be announced soon and I don't know the number
current volunteers of hand, but I can probably find out.

**Comment by DeLongShot** [comment]
Looks like we have just over 70 attendees at this point.  We're looking to
get about 140 signups this year, so if you think you might be able to come
and contribute, please register online and let us know.  Also, I should
mention GRGiveCamp is November 8-10 at The Factory downtown (right next to
Adtegrity).  http://grgivecamp.org/register-volunteers.html

Thanks!

**Comment by matthew-p** [comment]
Registered, for what it's worth.

http://www.linkedin.com/pub/matthew-pische/13/ab3/409

**Comment by ThomasBush** [comment]
@DeLongShot are we supposed to be at that meeting tomorrow if we volunteered?  I don't think I ever received confirmation after signing up - can't find it in my email, maybe I deleted it?  After receiving that email today I was a bit confused.  I couldn't find information on the site for those that have already signed up - just a form to get you to register.  Do you have a schedule?

**Comment by jasonrwagner** [comment]
I'm in.  I went last year and learned a lot.  It's good people and a good
time!

**Comment by atkolkma** [comment]
Just registered. There's a meeting tomorrow? Please clarify on this,
because I had no idea about it.

-Adam

**Comment by DeLongShot** [comment]
Tom and for anyone else who volunteered,

No, you do not have to be at the meeting tomorrow if you registered for the
event in November.  However, we are looking for volunteers who could help
out tomorrow with orientation for the non-profits.

Tomorrow is an orientation for the non-profits who we will be working with
in November just to get them ready for the event.  Things like managing
expectations, more requirements gathering if needed, where to find the
appropriate info about your website that we need (hostname, logins,
databases, etc.) and others.

Orientation goes from 10-2, but you can volunteer for however long you can
be there.  Lunch will be provided.  If you have time and would like to
volunteer, that would be great, but it is not required.

**Comment by DeLongShot** [comment]
P.S.  We could REALLY use some more volunteers tomorrow if you have time at
all.  Thanks for helping support this event.  Have a good weekend.

**Comment by atkolkma** [comment]
Is this at the factory? What time should we get there if the event starts
at 10am?

-Adam

**Comment by DeLongShot** [comment]
Yep.  You should plan on getting there 5 minutes early just to be safe.
 However, parking at The Factory can be tricky.  There's no official
parking lot so, meters are free in some spots on the weekend, and there are
lots available, but give yourself some time to park.

Forgot.  Here's the sign-up form if you would like volunteer tomorrow.
 There's a list of the NPOs for this year as well.
https://docs.google.com/forms/d/1uUd17GghWLvJZ4tqX7EnNw60VUHmaLQdjXdTpUwpKYs/viewform

**Comment by chiperific** [comment]
Adam,

There is a non-profit orientation tomorrow at the Factory from 10am to 2pm. It would be great if you could join us!

Chip Kragt

chiperific@gmail.com

616-813-8140

**Comment by billgathen** [comment]
Last-minute nudge! [GiveCamp](http://grgivecamp.org) apparently has 117 devs/designers signed-up and are trying to push that to 150.

If you're still on the fence, jump in! If you know someone else who'd be an asset, make sure they know about it.

Those of you that have already committed, I'll see you there!
