### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ThomasBush** [WestMichiganRubyTraining/discussion#8]
Trying to run through fizzbuzz so I can have it down.  Ran into an error that I cant seem to solve.  I am a bit frustrated because I have gotten further than this before, but can't see my mistake.  I guess that proves why its best to keep up the repetition.  Anyways, anyone see anything here?

``` ruby
require 'json'

class Fizzbuzz
    def initialize
        @output_array = []
    end

    def iterator (last_num)
        (1..last_num).map do |n|
            if n % 3 == 0 && n % 5 == 0
                @output_array << "FizzBuzz"
            elsif n % 3 == 0
                @output_array << "Fizz"
            elsif n % 5 == 0
                @output_array << "Buzz"
            else
                @output_array << n.to_s
            end
        end
    end

    def to_html
        convert_to_html << "<ul>\n"
        @output_array.each do |item|
            convert_to_html << "    <li> #{item} </li>\n"   
        end
        convert_to_html << "</ul>"
    end

    def output
        puts @output_array.join(" ")
        puts @output_array.to_json
        puts @output_array.to_html
    end


end

myFizzBuzzInstance = Fizzbuzz.new()
myFizzBuzzInstance.iterator(15)
myFizzBuzzInstance.output
```

My error tells me that "to_html" is not defined which isn't the case, so where is my mistake?  Thanks for any help you can provide.

**Comment by billgathen** [comment]
`@output_array.to_html` should be `to_html(@output_array)`

to_html is a method on Fizzbuzz, not array. ;-)

Kudos for working through it, and for asking for help when you get stuck.

"The sweat we spill today is payment on our victories of tomorrow."

**Comment by coderbydesign** [comment]
One small tweak to Bill's solution is that since `@output_array` is an instance variable, you don't need to pass it in as an argument to `to_html` since it will be accessible anywhere in that instance of Fizzbuzz. This would work:

```
def output
  puts @output_array.join(" ")
  puts @output_array.to_json
  puts to_html
end
```

Keep it up!

**Comment by billgathen** [comment]
Doh! Always run your code before posting! :-)

Good catch, Keith.

**Comment by ThomasBush** [comment]
Alright I hope you guys don't mind but I have another error and this is much more foreign territory as this is the first time I have gotten to the testing section of 7DFB.  

I have made corrections as suggested (thanks Keith and Bill)

Here is my test:

``` ruby
describe Fizzbuzz do
    it "should return the corect output for each input" do
        expect{fizzbuzz_a_number_conditional(9)}.to eq("Fizz")
        expect{fizzbuzz_a_number_conditional(10)}.to eq("Buzz")
        expect{fizzbuzz_a_number_conditional(11)}.to eq("11")
        expect{fizzbuzz_a_number_conditional(30)}.to eq("FizzBuzz")
    end
end
```

Here is the new method created after using the extract method of refactoring as highlighted by Bill last night. 

``` ruby
def fizzbuzz_a_number_conditional(n)
    if n % 3 == 0 && n % 5 == 0
        "FizzBuzz"
    elsif n % 3 == 0
        "Fizz"
    elsif n % 5 == 0
        "Buzz"
    else
        n.to_s
    end
end
```

And of course my failure:

``` ruby
Failures:

  1) Fizzbuzz should return the corect output for each input
     Failure/Error: expect{fizzbuzz_a_number_conditional(9)}.to eq("Fizz")

       expected: "Fizz"
            got: #<Proc:0x007fa8dbadc5b0@/Users/tombush/Documents/Development/meetup/spec/fizzbuzz_spec.rb:5>

       (compared using ==)
     # ./spec/fizzbuzz_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.0007 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/fizzbuzz_spec.rb:4 # Fizzbuzz should return the corect output for each input
```

I am not entire sure I under stand proc objects and google searches for this error are not seeming to help.  Why does  rspec tell me I only have 1 example? I was under the impression that I had 4 examples there.  I am trying to use the expect syntax that Zach highlighted - is this incorrect?  Also why do I get a proc object back?  When I just run the fizzbuzz.rb I still get correct output - could this be an issue with me class initializer? 

Sorry I think I have a lot of questions there, but I really appreciate the help.

**Comment by coderbydesign** [comment]
Instead of `expect{fizzbuzz_a_number_conditional(9)}.to eq("Fizz")` you should use `expect(fizzbuzz_a_number_conditional(9)).to eq("Fizz")` where the curly braces are replaced with parens.

`expect()` will evaluate the return value, whereas `expect{}` is returning the proc object, which is useful for testing exceptions and other things apart from the return value.

**Comment by ThomasBush** [comment]
Still having issues and everything I find on google points to rails implementations.

fizzbuzz.rb

``` ruby
require 'json'
require 'rspec'

class Fizzbuzz
    def initialize(last_num)
        @output_array = []
        @last_num = last_num
    end

    def fizzbuzz_a_number_conditional(n)
        if n % 3 == 0 && n % 5 == 0
            "FizzBuzz"
        elsif n % 3 == 0
            "Fizz"
        elsif n % 5 == 0
            "Buzz"
        else
            n.to_s
        end
    end

    def iterator
        (1..@last_num).map do |n|
            @output_array << fizzbuzz_a_number_conditional(n)
        end
    end

    def to_html
        convert_to_html = []
        convert_to_html << "<ul>\n"
        @output_array.each do |item|
            convert_to_html << "    <li>#{item}</li>\n" 
        end
        convert_to_html << "</ul>"
    end

    def output
        puts @output_array.join(" ")
        puts @output_array.to_json
        puts to_html
    end


end

myFizzBuzzInstance = Fizzbuzz.new(15)
myFizzBuzzInstance.iterator
myFizzBuzzInstance.output
```

spec/fizzbuzz_spec.rb

``` ruby
require 'spec_helper'

describe Fizzbuzz do
    describe 'when fizzbuzz a number Function runs' do
        it 'should return the corect output for each input' do
            expect(fizzbuzz_a_number_conditional(9)).to eq("Fizz")
            expect(fizzbuzz_a_number_conditional(10)).to eq("Buzz")
            expect(fizzbuzz_a_number_conditional(11)).to eq("11")
            expect(fizzbuzz_a_number_conditional(30)).to eq("FizzBuzz")
        end
    end
end
```

spec/spec_helper.rb just simply includes my fizzbuzz ruby file which I thought would clear up my problem

``` ruby
require_relative '../fizzbuzz'
```

My output looks like this:  

``` ruby
$ rspec spec
1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz
["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]
<ul>
    <li>1</li>
    <li>2</li>
    <li>Fizz</li>
    <li>4</li>
    <li>Buzz</li>
    <li>Fizz</li>
    <li>7</li>
    <li>8</li>
    <li>Fizz</li>
    <li>Buzz</li>
    <li>11</li>
    <li>Fizz</li>
    <li>13</li>
    <li>14</li>
    <li>FizzBuzz</li>
</ul>
F

Failures:

  1) Fizzbuzz when fizzbuzz a number Function runs should return the corect output for each input
     Failure/Error: expect(fizzbuzz_a_number_conditional(9)).to eq("Fizz")
     NoMethodError:
       undefined method `fizzbuzz_a_number_conditional' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007fc8812dacc0>
     # ./spec/fizzbuzz_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.00031 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/fizzbuzz_spec.rb:5 # Fizzbuzz when fizzbuzz a number Function runs should return the corect output for each input
```

Why does it not recognize the method? Why does it say its only running one example instead of what I would think are 4 examples - is this because there is only one "it" block?

**Comment by DavidBechtel** [comment]
Thomas,

  In your spec, within your describe, you need to create a FizzBuzz instance and call the fizzbuzz_a_number within your instance.

**Comment by billgathen** [comment]
First comment out the last 3 lines of your file: they get executed when your file gets loaded, which is why that output shows up even though you didn't run the file. See the `if __FILE__ == $0` convention to have it both ways.

Remove `require 'rspec'` from your class file. Your code should never depend on test frameworks. Even spec files don't need it, because running `rspec spec` includes rspec implicitly.

In fizzbuzz_spec.rb, replace `require 'spec_helper'` with `require_relative '../fizzbuzz'`: with such a simple example you don't need spec_helper. Require_relative uses the current file as the base for the path, which is why you need the `../` to get back to the base directory from `spec/`.

Finally, as Dave says, you can either use a `let` or a `before` clause to create an instance of your Fizzbuzz object. Remember to pass it an argument, even though you don't use it in your test.

Keep plugging! You'll get it!

**Comment by coderbydesign** [comment]
For your last question regarding the number of test examples, you are correct. Each `it` block represents a new spec.

**Comment by ThomasBush** [comment]
Perfect, thanks all, made all changes recommended by Dave and Bill.  Created a instance in a let block and got the first set of specs passing!!!  Now, onto the next one.  

I appreciate you clearing that up Keith, just wanted to wrap my head around this a little better...

Thanks guys.

**Comment by billgathen** [comment]
Crowdsourcing FTW!

## 
- Bill\* *
  http://billgathen.com

**Comment by billgathen** [comment]
Tom, if you've got the answers you need, feel free to close this to keep the issue queue tidy. You can always re-open it later or create a new issue if you have more questions. :-)

**Comment by ThomasBush** [comment]
Alrighty, thanks
