### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by billgathen** [WestMichiganRubyTraining/discussion#9]
I've tweaked the ownership of the repo, so hopefully you'll all get notifications when something is posted: Keith pointed out that he only got alerts after he'd posted to a topic.

Can I get a response to make sure it's working?

**Comment by coderbydesign** [comment]
I received a notification!

**Comment by andrewbredow** [comment]
Got it!

**Comment by jasonrwagner** [comment]
I got it too.

**Comment by DavidBechtel** [comment]
Hello, I got the message below!
